services:
  database:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: barrage_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: barrage_flow_db_AI_Version
    #  ports supprimés
     volumes:
      - mysql_data:/var/lib/mysql
      - ./database/sql/06_app_user.sql:/docker-entrypoint-initdb.d/06_app_user.sql

  api:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: barrage_api
    restart: always
    environment:
       DATABASE_URL: mysql+pymysql://barrage_app:AppSecure2024!@database:3306/barrage_flow_db_AI_Version
       SECRET_KEY: supersecretkey
    ports:
      - "8000:8000"
    depends_on:
      - database

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: barrage_pma
    restart: always
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: root_password
      PMA_DB: barrage_flow_db_AI_Version
    ports:
      - "8080:80"
    depends_on:
      - database

volumes:
  mysql_data: